// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuT6UJ4azb3h0tauuIXjrZDXyh116xzHU',
    appId: '1:679271016710:web:cedc09d492527185299687',
    messagingSenderId: '679271016710',
    projectId: 'my-portfolio-c788b',
    authDomain: 'my-portfolio-c788b.firebaseapp.com',
    databaseURL: 'https://my-portfolio-c788b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-portfolio-c788b.appspot.com',
    measurementId: 'G-XK82LZP594',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHvMokmCpWpyTXgcC3YJi2CPz3LQGshng',
    appId: '1:679271016710:android:8a379b093793ed66299687',
    messagingSenderId: '679271016710',
    projectId: 'my-portfolio-c788b',
    databaseURL: 'https://my-portfolio-c788b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-portfolio-c788b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnuXpV08h5_UbIKw3LQNx3RAGMIXP3lbg',
    appId: '1:679271016710:ios:516bedfa4e26fc51299687',
    messagingSenderId: '679271016710',
    projectId: 'my-portfolio-c788b',
    databaseURL: 'https://my-portfolio-c788b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-portfolio-c788b.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnuXpV08h5_UbIKw3LQNx3RAGMIXP3lbg',
    appId: '1:679271016710:ios:50e57f44957c56c5299687',
    messagingSenderId: '679271016710',
    projectId: 'my-portfolio-c788b',
    databaseURL: 'https://my-portfolio-c788b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-portfolio-c788b.appspot.com',
    iosBundleId: 'com.example.myPortfolio.RunnerTests',
  );
}
