name: Flutter Build & Deploy

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'  # Replace with your desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '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'
          publish_dir: build/web
